sebersole/hibernate-orm

hibernate-core/src/test/java/org/hibernate/test/annotations/ConfigurationTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/EntityTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/beanvalidation/DDLWithoutCallbackTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/immutable/ImmutableTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/join/JoinTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetomany/OneToManyTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OptionalOneToOneMappedByTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OptionalOneToOnePKJCTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/hhh9798/OneToOneJoinTableTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/override/AssociationOverrideTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/tableperclass/TablePerClassTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/uniqueconstraint/UniqueConstraintTest.java, hibernate-core/src/test/java/org/hibernate/test/any/AnyTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/cut/CompositeUserTypeTest.java, hibernate-core/src/test/java/org/hibernate/test/immutable/ImmutableTest.java, hibernate-core/src/test/java/org/hibernate/test/immutable/entitywithmutablecollection/AbstractEntityWithManyToManyTest.java, hibernate-core/src/test/java/org/hibernate/test/immutable/entitywithmutablecollection/AbstractEntityWithOneToManyTest.java, hibernate-core/src/test/java/org/hibernate/test/interceptor/InterceptorTest.java, hibernate-core/src/test/java/org/hibernate/test/jpa/cascade/CascadeTest.java, hibernate-core/src/test/java/org/hibernate/test/jpa/naturalid/ImmutableNaturalIdTest.java, hibernate-core/src/test/java/org/hibernate/test/legacy/FooBarTest.java, hibernate-core/src/test/java/org/hibernate/test/manytomanyassociationclass/surrogateid/generated/ManyToManyAssociationClassGeneratedIdTest.java, hibernate-core/src/test/java/org/hibernate/test/naturalid/immutable/ImmutableEntityNaturalIdTest.java, hibernate-core/src/test/java/org/hibernate/test/ops/CreateTest.java, hibernate-core/src/test/java/org/hibernate/test/ops/MergeMultipleEntityCopiesAllowedTest.java, hibernate-core/src/test/java/org/hibernate/test/ops/MergeTest.java, hibernate-core/src/test/java/org/hibernate/test/optlock/OptimisticLockTest.java, hibernate-core/src/test/java/org/hibernate/test/readonly/ReadOnlyProxyTest.java, hibernate-core/src/test/java/org/hibernate/test/sql/autodiscovery/AutoDiscoveryTest.java
just to be sure I'm doing right :)
=> Fix DDLWithoutCallbackTest

hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java
Not entirely sure you wanted this ported, but I went ahead and ported it from AbstractQueryImpl, tweaking the deprecated calls with the suggested 5.2 methods.
=> FIx setProperties functionality.

hibernate-core/src/main/java/org/hibernate/internal/SessionImpl.java, hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/transaction/TransactionJoinHandlingChecker.java, hibernate-entitymanager/src/test/java/org/hibernate/jpa/test/transaction/TransactionJoiningTest.java
=> Fix test transactionCoordinator.isActive() check

hibernate-core/src/main/java/org/hibernate/boot/internal/AttributeConverterDescriptorNonAutoApplicableImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/FilterDefinitionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ResultSetMappingBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/type/internal/BasicTypeProducerRegistryImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/type/internal/BasicTypeProducerTypeDefinitionImpl.java, hibernate-core/src/main/java/org/hibernate/boot/spi/AbstractDelegatingMetadata.java, hibernate-core/src/main/java/org/hibernate/cache/internal/OldCacheKeyImplementation.java, hibernate-core/src/main/java/org/hibernate/cache/internal/OldNaturalIdCacheKey.java, hibernate-core/src/main/java/org/hibernate/cache/spi/QueryKey.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/Configuration.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/ResultsetMappingSecondPass.java, hibernate-core/src/main/java/org/hibernate/engine/spi/CollectionKey.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EntityKey.java, hibernate-core/src/main/java/org/hibernate/engine/spi/EntityUniqueKey.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/type/CollectionType.java, hibernate-core/src/main/java/org/hibernate/type/TypeHelper.java
Other compilation errors fixed, not sure about AttributeConverterDescriptorNonAutoApplicableImpl
=> HHH-10873 - Type systems consolidation + org.hibernate.type refactoring

hibernate-core/src/main/java/org/hibernate/engine/internal/UnsavedValueFactory.java, hibernate-core/src/main/java/org/hibernate/param/VersionTypeSeedParameterSpecification.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/ByteJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/DateJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/InstantJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/IntegerJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/LocalDateTimeJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/LongJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/OffsetDateTimeJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/PrimitiveByteArrayJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/internal/ShortJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/BasicJavaDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/descriptor/java/spi/JavaTypeDescriptor.java, hibernate-core/src/main/java/org/hibernate/type/internal/BasicTypeImpl.java, hibernate-core/src/main/java/org/hibernate/type/spi/BinaryVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/ByteVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/CalendarVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/InstantVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/IntegerVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/LocalDateTimeVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/LongVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/OffsetDateTimeVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/ShortVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/TimestampVersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/VersionSupport.java, hibernate-core/src/main/java/org/hibernate/type/spi/ZonedDateTimeVersionSupport.java
@sebersole not yet finished, want your opinion before going on with all the other types needing VersionSupport
=> HHH-10873 - VersionSupport

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/boot/internal/MetadataBuildingContextRootImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/TypeDefinition.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/MappingDocument.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/ModelBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/hbm/TypeDefinitionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/type/internal/TypeDefinitionRegistryImpl.java, hibernate-core/src/main/java/org/hibernate/boot/model/type/spi/TypeDefinitionRegistry.java, hibernate-core/src/main/java/org/hibernate/boot/model/type/spi/TypeResolverTemplate.java, hibernate-core/src/main/java/org/hibernate/boot/spi/InFlightMetadataCollector.java, hibernate-core/src/main/java/org/hibernate/boot/spi/MetadataBuildingContext.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/SimpleValueBinder.java, hibernate-core/src/main/java/org/hibernate/type/internal/BasicTypeImpl.java, hibernate-core/src/main/java/org/hibernate/type/spi/BasicType.java, hibernate-core/src/main/java/org/hibernate/type/spi/ParameterizedType.java
For suggestions/input/feedback.
=> HHH-10873 - Introduce TypeDefinitionRegistry

hibernate-core/src/main/java/org/hibernate/engine/internal/StatefulPersistenceContext.java, hibernate-core/src/main/java/org/hibernate/envers/query/criteria/internal/SimpleAuditExpression.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/CollectionElementEmbeddedImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/CollectionElementEntityImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/CollectionIndexEmbeddedImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/CollectionIndexEntityImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntityIdentifierCompositeAggregatedImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntityIdentifierCompositeNonAggregatedImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularPersistentAttributeEmbedded.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularPersistentAttributeEntity.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/spi/AbstractPluralPersistentAttribute.java, hibernate-core/src/main/java/org/hibernate/sql/ast/produce/sqm/internal/PolymorphicEntityValuedExpressableTypeImpl.java, hibernate-core/src/main/java/org/hibernate/sql/results/internal/JdbcValuesSourceProcessingStateStandardImpl.java
@sebersole I made a PR just in case you have already done these changes locally, I hope not :)
=> HHH-10954 Integrate SQM into Hibernate ORM

hibernate-core/src/main/java/org/hibernate/boot/internal/InFlightMetadataCollectorImpl.java, hibernate-core/src/main/java/org/hibernate/cfg/AnnotationBinder.java, hibernate-core/src/main/java/org/hibernate/cfg/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/cfg/IdGeneratorResolverSecondPass.java, hibernate-core/src/main/java/org/hibernate/cfg/annotations/IdBagBinder.java, hibernate-core/src/test/java/org/hibernate/jpa/test/cascade/MergeWithTransientNonCascadedAssociationTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/graphs/mapped_by_id/LoadGraphFindByIdTest.java, hibernate-core/src/test/java/org/hibernate/test/annotations/onetoone/OwnerAddress.java, hibernate-core/src/test/java/org/hibernate/test/inheritance/relationship/JoinedInheritanceWithOneToManyTest.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithBidirectionalOneToManyFlushProblem.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithCascadeOnPersist.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithJoinedTableInheritance.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithJoinedTableMultiLevelInheritance.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithSingleTableInheritance.java, hibernate-core/src/test/java/org/hibernate/test/insertordering/InsertOrderingWithTablePerClassInheritance.java, hibernate-core/src/test/java/org/hibernate/test/jpa/compliance/tck2_2/TableGeneratorMultipleDefinitionTest.java, hibernate-core/src/test/java/org/hibernate/test/jpa/compliance/tck2_2/TableGeneratorVisibilityTest.java
https://hibernate.atlassian.net/browse/HHH-12157
=> HHH-12157 - TableGenerator defined on one class is not visible on another

hibernate-core/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/ClassAuditingData.java, hibernate-core/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/ComponentAuditingData.java, hibernate-core/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/PropertyAuditingData.java, hibernate-core/src/main/java/org/hibernate/envers/internal/entities/PropertyData.java, hibernate-core/src/main/java/org/hibernate/envers/internal/entities/RevisionTimestampData.java, hibernate-core/src/main/java/org/hibernate/envers/internal/entities/mapper/id/VirtualEntitySingleIdMapper.java, hibernate-core/src/main/java/org/hibernate/envers/internal/synchronization/work/AddWorkUnit.java, hibernate-core/src/main/java/org/hibernate/envers/internal/tools/EntityTools.java, hibernate-core/src/main/java/org/hibernate/envers/query/criteria/internal/CriteriaTools.java
Fix envers compilation errors.  There are a few errors in o.h.envers that depend on changes that are included in https://github.com/sebersole/hibernate-core/pull/118
=> fix compilation errors.

hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/SingularPersistentAttributeEntity.java, hibernate-core/src/main/java/org/hibernate/query/sqm/tree/from/SqmFromElementSpace.java, hibernate-core/src/main/java/org/hibernate/sql/ast/produce/metamodel/internal/MetamodelSelectBuilderProcess.java, hibernate-core/src/main/java/org/hibernate/sql/ast/produce/metamodel/spi/AssociationKey.java, hibernate-core/src/main/java/org/hibernate/sql/ast/produce/metamodel/spi/Fetchable.java, hibernate-core/src/main/java/org/hibernate/sql/ast/produce/sqm/spi/SqmSelectToSqlAstConverter.java, hibernate-core/src/test/java/org/hibernate/orm/test/crud/EntityWithBidirectionalOneToOneTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/crud/EntityWithLazyManyToOneSelfReferenceCrudTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/crud/EntityWithLazyOneToOneTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/crud/EntityWithOneToOneTest.java, hibernate-core/src/test/java/org/hibernate/orm/test/support/domains/gambit/EntityWithLazyManyToOneSelfReference.java
@sebersole not sure if what I'm doing in this PR is correct, it solves some issues with circular references but it is not working for EntityWithManyToOneSelfReferenceCrudTest 
I'll keep on working on it on Tuesday, if you have time to give a look any suggestion is well accepted :) 
Thanks
=> OneToOne fetches circular references

hibernate-core/src/main/java/org/hibernate/engine/spi/SessionFactoryImplementor.java, hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/JpaMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AbstractPluralAttribute.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/AttributeFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/DomainMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MapAttributeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/DomainMetamodel.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/jpa/test/criteria/QueryBuilderTest.java, hibernate-core/src/test/java/org/hibernate/jpa/test/metadata/MetadataTest.java
Hi Steve,
during my flight I worked on the `JpaMetamodelImpl` and `DomainMetamodelImpl`.
for `JpaMetamodelImpl` I'm not sure if there is a better way to initialize it and plus I have not found a good solution for the `entityProxyInterfaceMap` (basically where to place it `JpaMetamodelImpl` or `DomainMetamodelImpl`?)
for `DomainMetamodelImpl` there are few `DomainMetamodel` methods that I was not sure how to implement.
=> JpaMetamodel and DomainMetamodelImpl

hibernate-core/src/main/java/org/hibernate/internal/SessionFactoryImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/AttributeFactory.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/InflightRuntimeMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/MetadataContext.java, hibernate-core/src/main/java/org/hibernate/metamodel/internal/RuntimeModelCreationProcess.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractDomainType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractIdentifiableType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/AbstractManagedType.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/JpaMetamodel.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/DomainMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EmbeddableTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/EntityTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/JpaMetamodelImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/model/domain/internal/MappedSuperclassTypeImpl.java, hibernate-core/src/main/java/org/hibernate/metamodel/spi/MetamodelImplementor.java, hibernate-core/src/main/java/org/hibernate/type/AssociationType.java, hibernate-core/src/main/java/org/hibernate/type/spi/TypeConfiguration.java, hibernate-core/src/test/java/org/hibernate/jpa/test/metadata/MetadataTest.java
@sebersole it is not yet fully completed, JpaMetamodelImpl and DomainMetamodelImpl do not implements all the superclasses methods.
And I have not yet plugged in the `RuntimeModelCreationProcess`.
=>  6 - SQM based on JPA type system,  RuntimeModelCreationProcess

local-build-plugins/src/main/java/org/hibernate/orm/properties/SettingsCollector.java, local-build-plugins/src/main/java/org/hibernate/orm/properties/SettingsDocGeneratorTask.java
=> HHH-17047 - Follow up tasks for Gradle 8.2 upgrade

hibernate-core/src/main/java/org/hibernate/boot/jaxb/mapping/spi/JaxbPluralAttribute.java, hibernate-core/src/main/resources/org/hibernate/xsd/mapping/mapping-3.2.0.xsd, hibernate-core/src/main/xjb/mapping-bindings.xjb
Changes needed to integrate the work previously done with https://github.com/sebersole/hibernate-models2/pull/66 and further plural attribute processing.
=> Small JAXB changes needed for plural attribute processing

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
@sebersole this PR fixes:
- NewlyInstantiatdCollectionSkipDeleteOrphanTest#VersionedMappingUnversionedParentSaveUpdate
- NewlyInstantiatdCollectionSkipDeleteOrphanTest#VersionedMappingVersionedParentSaveUpdate
=> HHH-17504 - fix issue with mapsid 

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
This Pr fixes : 
- CompositeIdFkGeneratedValueIdentityTest. testCompositePkWithIdentityAndFKByIdentity2(SessionFactoryScope)
- CompositeIdFkGeneratedValueTest. testCompositePkWithIdentityAndFKByAuto(SessionFactoryScope)
- CompositeIdFkGeneratedValueTest. testCompositePkWithIdentityAndFKByAuto2(SessionFactoryScope)
- CompositeIdFkGeneratedValueTest. testCompositePkWithIdentityAndFKBySequence(SessionFactoryScope)
- CompositeIdFkGeneratedValueTest. testCompositePkWithIdentityAndFKByTable(SessionFactoryScope)
- CompositeIdFkGeneratedValueTest. testCompositePkWithIdentityAndFKByTable2(SessionFactoryScope)
- CompositeIdFkGeneratedValueTest. testCompositePkWithSequenceIdentifierGeneratorAndFKBySequence2(SessionFactoryScope)
- CompositeIdFkGeneratedValueTest. …
=> Fix idClass mapping

hibernate-core/src/main/java/org/hibernate/boot/model/internal/AbstractPropertyHolder.java
This PR fixed :
- CompositeIdTest. initializationError
- OverrideOneToOneJoinColumnTest. disallowOnSideWithMappedBy()
- ReferencedColumnNameTest. initializationError
- EmbeddedOverrideTests. initializationError
- MappedSuperclassOverrideTests. initializationError
- AssociationOverrideSchemaTest. testJoinTableJoinColumnName
- AssociationOverrideSchemaTest. testJoinTableSchemaName
- AssociationOverrideTest. testSchemaCreation(SessionFactoryScope)
=> HHH-17504 Fix AttributeOverride

hibernate-core/src/main/java/org/hibernate/boot/model/internal/ColumnsBuilder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java
same as https://github.com/sebersole/hibernate-orm/pull/207 that seems got lost during rebase
=> HHH-17504 Fix mapId

hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java
This PR relies on https://github.com/hibernate/hibernate-models/pull/40
=> HHH-17504 - Fix EntityBinder#applyTypeBinder

hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlAnnotationHelper.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/XmlProcessingHelper.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/attr/ElementCollectionAttributeProcessing.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/db/ColumnProcessing.java
this PR fixes:
- ElementCollectionConverterTest. initializationError
- XmlAccessTest. testAccessOnElementCollectionXmlElement(
=> HHH-17504 - Fix issues with elementcollection 

hibernate-core/hibernate-core.gradle, hibernate-core/src/main/java/org/hibernate/boot/model/internal/BinderHelper.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/ClassPropertyHolder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/CollectionBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EmbeddableBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/EntityBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/IdBagBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyBinder.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyContainer.java, hibernate-core/src/main/java/org/hibernate/boot/model/internal/PropertyInferredData.java, hibernate-core/src/main/java/org/hibernate/mapping/SimpleValue.java, hibernate-core/src/main/java/org/hibernate/type/internal/ParameterizedTypeImpl.java, settings.gradle
Work on generics and type resolution.
Requires https://github.com/hibernate/hibernate-models/pull/42 to be merged and released.
=> HHH-17460 - Ongoing JPA 32 work

hibernate-core/src/main/java/org/hibernate/boot/model/internal/JPAXMLOverriddenAnnotationReader.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/ManagedTypeProcessor.java, hibernate-core/src/main/java/org/hibernate/boot/models/xml/internal/attr/ElementCollectionAttributeProcessing.java, settings.gradle
- Fix missing Emneddable annotation for xml override
- Fix annoationUsage default ClassDetails value 
- upgrade hibernate-models to 0.7.2
=> Various fixes

hibernate-envers/src/main/java/org/hibernate/envers/boot/internal/EnversMetadataBuildingContextImpl.java, hibernate-envers/src/main/java/org/hibernate/envers/boot/spi/EnversMetadataBuildingContext.java, hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/ModelsHelper.java, hibernate-envers/src/main/java/org/hibernate/envers/configuration/internal/metadata/reader/AuditedPropertiesReader.java
Feel free to squash this into your main commit 😃
=> Use ModelsContext in Envers
